<a href="https://colab.research.google.com/github/aarmentamna/PY0101EN/blob/main/M5SimpleAPIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Simple APIs
## **Random User and Fruitvice API Examples**

Example 1: RandomUser API

In [1]:
!pip install randomuser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5084 sha256=a7013b19f12d7bda0f5be1798aa2da371c01f0c400904ae147368f02b0802b17
  Stored in directory: /root/.cache/pip/wheels/21/10/7b/c13bc3e24a3c1000a34554802ad8aa0ff27df56366998a0473
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [2]:
from randomuser import RandomUser
import pandas as pd

In [3]:
r = RandomUser()

In [4]:
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x7fbf5a5e7210>,
 <randomuser.RandomUser at 0x7fbf5a5e7250>,
 <randomuser.RandomUser at 0x7fbf5a5e7290>,
 <randomuser.RandomUser at 0x7fbf5a5e72d0>,
 <randomuser.RandomUser at 0x7fbf5a5e7310>,
 <randomuser.RandomUser at 0x7fbf5a5e7390>,
 <randomuser.RandomUser at 0x7fbf5a5e73d0>,
 <randomuser.RandomUser at 0x7fbf5a5e7410>,
 <randomuser.RandomUser at 0x7fbf5a5e7450>,
 <randomuser.RandomUser at 0x7fbf5a5e7350>]

In [6]:
name = r.get_full_name()
name

'Ömür Samancı'

In [7]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Sasha Morel   sasha.morel@example.com
David Ortega   david.ortega@example.com
Marit Gebert   marit.gebert@example.com
Kenan Hinna   kenan.hinna@example.com
Alfred Dunn   alfred.dunn@example.com
Werner Moor   werner.moor@example.com
Millie Walker   millie.walker@example.com
Daniel Gerard   daniel.gerard@example.com
Norah Renard   norah.renard@example.com
Emilie Chan   emilie.chan@example.com

In [8]:
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/women/76.jpg
https://randomuser.me/api/portraits/men/80.jpg
https://randomuser.me/api/portraits/men/63.jpg
https://randomuser.me/api/portraits/men/20.jpg
https://randomuser.me/api/portraits/women/63.jpg
https://randomuser.me/api/portraits/men/48.jpg
https://randomuser.me/api/portraits/women/40.jpg
https://randomuser.me/api/portraits/women/56.jpg

In [9]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [10]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Emma Perry,female,Ballybofey-Stranorlar,Roscommon,emma.perry@example.com,1976-12-30T14:30:27.644Z,https://randomuser.me/api/portraits/women/70.jpg
1,Alberto Long,male,Bathurst,Queensland,alberto.long@example.com,1966-03-21T04:25:45.360Z,https://randomuser.me/api/portraits/men/93.jpg
2,Naomi Overå,female,Skjervøy,Vestfold,naomi.overa@example.com,1998-03-15T12:22:53.725Z,https://randomuser.me/api/portraits/women/52.jpg
3,Aiden Wong,male,Clinton,Québec,aiden.wong@example.com,1962-07-27T21:09:13.329Z,https://randomuser.me/api/portraits/men/1.jpg
4,Marlene Larsson,female,Elnesvågen,Hordaland,marlene.larsson@example.com,1948-03-13T12:31:05.165Z,https://randomuser.me/api/portraits/women/8.jpg
5,Giray Eliçin,male,Amasya,Erzincan,giray.elicin@example.com,1991-07-13T16:59:24.662Z,https://randomuser.me/api/portraits/men/18.jpg
6,Deniz Erbulak,male,Bayburt,Kırklareli,deniz.erbulak@example.com,1957-11-23T18:10:02.497Z,https://randomuser.me/api/portraits/men/28.jpg
7,Ella Turner,female,Shannon,Longford,ella.turner@example.com,1952-09-08T12:42:17.714Z,https://randomuser.me/api/portraits/women/63.jpg
8,Gregory James,male,Townsville,Western Australia,gregory.james@example.com,1948-09-07T04:12:41.198Z,https://randomuser.me/api/portraits/men/28.jpg
9,Adham Verdoorn,male,Elshout,Zeeland,adham.verdoorn@example.com,1982-10-26T16:59:50.723Z,https://randomuser.me/api/portraits/men/11.jpg

In [12]:
df1 = pd.DataFrame(get_users())  
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Valtteri Haataja,male,Akaa,Lapland,valtteri.haataja@example.com,1953-11-25T15:21:17.527Z,https://randomuser.me/api/portraits/men/52.jpg
1,Sena Kaashoek,female,Notter,Groningen,sena.kaashoek@example.com,1983-07-16T21:52:43.281Z,https://randomuser.me/api/portraits/women/83.jpg
2,Valentina Sheikh,female,Bjervamoen,Telemark,valentina.sheikh@example.com,1987-01-14T00:34:50.399Z,https://randomuser.me/api/portraits/women/22.jpg
3,Joshua Lacroix,male,Brest,Aube,joshua.lacroix@example.com,1996-06-20T07:24:22.081Z,https://randomuser.me/api/portraits/men/50.jpg
4,Carlos Wacker,male,Bad Rodach,Saarland,carlos.wacker@example.com,1977-06-27T06:21:06.395Z,https://randomuser.me/api/portraits/men/60.jpg
5,Timothy Van der Kolk,male,Empel,Noord-Brabant,timothy.vanderkolk@example.com,1990-01-04T13:20:55.498Z,https://randomuser.me/api/portraits/men/36.jpg
6,Beatrice Pelletier,female,Cornwall,Yukon,beatrice.pelletier@example.com,1949-07-20T17:36:50.916Z,https://randomuser.me/api/portraits/women/3.jpg
7,Niilo Halonen,male,Loimaa,Finland Proper,niilo.halonen@example.com,1947-04-17T20:29:49.353Z,https://randomuser.me/api/portraits/men/84.jpg
8,Pihla Leinonen,female,Akaa,North Karelia,pihla.leinonen@example.com,1959-06-07T21:26:20.174Z,https://randomuser.me/api/portraits/women/25.jpg
9,Alicja Wulff,female,Lahnstein,Berlin,alicja.wulff@example.com,1987-10-08T15:11:53.155Z,https://randomuser.me/api/portraits/women/25.jpg

Example 2: Fruitvice API
Another, more common way to use APIs, is through requests library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [13]:
import requests
import json

In [14]:
data = requests.get("https://www.fruityvice.com/api/fruit/all")

In [15]:
results = json.loads(data.text)

In [16]:
pd.DataFrame(results)
pd

In [17]:
df2 = pd.json_normalize(results)
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
3,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
4,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
5,Prunus,Cherry,9,Rosaceae,None,12.00,1.00,0.30,50,8.00
6,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
7,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
8,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
9,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
10,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
11,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
12,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
13,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
14,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
15,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
16,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
17,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
18,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
19,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
20,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
21,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
22,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
23,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
24,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
25,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
26,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
27,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
28,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
29,Spondias,Umbu,73,Anacardiaceae,0,0.00,0.00,0.00,0,0.00
30,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

In [18]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

In [19]:
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96

Exercise 3
This page contains a list of free public APIs. Choose any API of your interest and use it to load/extract some information, as shown in the example above.

Using requests.get("url") function, load your data.

In [20]:
data2 = requests.get("https://www.fishwatch.gov/api/species")

In [21]:
results2 = json.loads(data2.text)

In [22]:
df3 = pd.DataFrame(results2)
df3

,Fishery Management,Habitat,Habitat Impacts,Image Gallery,Location,Management,NOAA Fisheries Region,Population,Population Status,Scientific Name,...,Selenium,Serving Weight,Servings,Sodium,Source,"Sugars, Total",Taste,Texture,Path,last_update
0,"<ul>\n<li><a href=""https://www.fisheries.noaa....",None,"Bottomfish fishing operations, typically using...",[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Crimson jobfish are distributed thro...,None,Pacific Islands,"The population level is unknown, but the stock...",<ul>\n<li>There are five stocks of crimson job...,Pristipomoides filamentosus,...,38.2 mcg,100 g (raw),1,64 mg,<p>U.S -wild caught around Hawaii and Pacific ...,0 g,<p>Crimson jobfish has a delicate flavor.</p>\n,<p>Crimson jobfish has&nbsp;a firm texture and...,/profiles/crimson-jobfish,06/21/2022 - 12:00
1,"<ul>\n<li><a href=""https://www.fisheries.noaa....","<ul>\n<li>White hake are groundfish, meaning t...",Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>White hake are found in the northwes...,None,Greater Atlantic,Significantly below target population level. A...,<ul>\n<li>According to the 2019 stock assessme...,Urophycis tenuis,...,32.1 mcg,100 g (raw),1,72 mg,<p>White hake is wild-caught from Maine to sou...,0 g,"<p>White hake has a mild, almost sweet&nbsp;ta...","<p>White hake has a soft, delicate texture tha...",/profiles/white-hake,03/24/2022 - 10:36
2,"<ul>\n<li>\n<p><a href=""https://archive.fisher...",<ul>\n<li>Atlantic chub mackerel are a schooli...,Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Atlantic chub mackerel in the wester...,None,Greater Atlantic,The stock has never been assessed. The popula...,<p>Atlantic chub mackerel has never been asses...,Scomber colias,...,44.1 mcg,100 g (raw),1,90 mg,<p>U.S. wild caught from Southern New England ...,0 g,"<p>Rich, pronounced flavor.</p>\n","<p>Soft, flaky, and moist.</p>\n",/profiles/atlantic-chub-mackerel,08/11/2022 - 16:16
3,"<ul>\n<li><a href=""https://www.fisheries.noaa....",<ul>\n<li>Shortfin squid live in deep and shal...,Fishing gears used to harvest shortfin squid h...,None,<ul>\n<li>Shortfin squid inhabits the continen...,None,Greater Atlantic,The population level is unknown. The species h...,<ul>\n<li>According to the latest assessment (...,Illex illecebrosus,...,44.8 mcg,100 g,1,44 mg,<p>U.S. wild-caught from Maine to North Caroli...,0 g,"<p>Mild, and subtly sweet.</p>\n<p>&nbsp;</p>\n",<p>Firm and meaty.</p>\n,/profiles/shortfin-squid,09/02/2022 - 11:08
4,"<ul>\n<li>The states and <a href=""https://www....",<ul>\n<li>American lobsters live on the ocean ...,Fishing gears used to harvest American lobster...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>American lobsters are found in the n...,None,Greater Atlantic,Above target population levels in the Gulf of ...,"<ul>\n<li>According to the 2020&nbsp;<a href=""...",Homarus americanus,...,41.4 mcg,100 g (raw),1,296 mg,<p>U.S. wild-caught from Maine to North Caroli...,0 g,<p>Mild and sweet.</p>\n,<p>The meat is firm and somewhat fibrous. The ...,/profiles/american-lobster,01/07/2022 - 10:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,"<ul>\n<li><a href=""https://www.fisheries.noaa....",<ul>\n<li>Younger pollock live in the mid-wate...,The Alaska pollock fishery uses midwater trawl...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Alaska pollock are found throughout ...,None,Alaska,Above target population levels for the Aleutia...,<ul>\n<li>There are five stocks of walleye pol...,Gadus chalcogrammus,...,21.9 mcg,100 g (raw),1,99 mg,"<p>U.S. wild-caught, mainly in the Bering Sea ...",0 g,<p>Pollock has mild-tasting flesh and is simil...,<p>Pollock has a relatively fine texture and i...,/profiles/alaska-pollock,08/24/2021 - 17:44
112,"<ul>\n<li><a href=""https://www.greateratlantic...","<ul>\n<li>Monkfish live on the ocean floor, ty...",Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Monkfish are found in the Northwest ...,None,"Greater Atlantic, Southeast",Above target population levels.,<ul>\n<li>There are two stocks of monkfish: Gu...,Lophius americanus,...,36.5 mcg,100 g (raw),1,18 mg,<p>U.S. wild-caught from Maine to North Caroli...,0 g,<p>Mild.</p>\n,"<p>The tail meat is firm, dense, and relativel...",/profiles/monkfish,08/10/2022 - 17:32
113,"<ul>\n<li><a href=""http://sero.nmfs.noaa.gov/""...",<ul>\n<li>Mahi mahi live near the surface in t...,Fishing gear used to catch mahi mahi rarely co...,[{'src': 'https://origin-east-01-drupal-fishwa...,"<ul>\n<li>Mahi mahi are found in the Atlantic,...",None,"Greater Atlantic, Southeast",Above target population levels.,<ul>\n<li>Scientists assume populations are ab...,Coryphaena hippurus,...,36.5 mcg,100 g (raw),1,88 mg,<p>Wild-caught from Massachusetts to Texas.</p>\n,0 g,"<p>Mahi mahi has a sweet, mild flavor. For a m...",<p>Mahi mahi is lean and fairly firm with larg...,/profiles/atlantic-mahi-mahi,08/03/2022 - 16:19
114,"<ul>\n<li><a href=""https://sero.nmfs.noaa.gov/...",<ul>\n<li>Cobia are found near structures in t...,Fishing gear used to catch cobia rarely contac...,[{'src': 'https://origin-east-01-drupal-fishwa...,"<ul>\n<li>In U.S. waters, cobia are most abund...",None,"Greater Atlantic, Southeast",Below target level but fishing rate promotes p...,<ul>\n<li>\n<p>According to the 2020 stock ass...,Rachycentron canadum,...,36.5 mcg,100 g (raw),1,135 mg,<p>Wild-caught from Virginia to Texas. Cobia i...,0 g,"<p>Cobia has a sweet, rich flavor.</p>\n","<p>Cobia is lean, moist, and firm with a nice ...",/profiles/cobia,02/17/2022 - 11:28
115,<ul>\n<li>There are two stocks of Atlantic cod...,<ul>\n<li>Atlantic cod live near the ocean flo...,Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,"<ul>\n<li>In the Northwest Atlantic, cod range...",None,Greater Atlantic,Significantly below target population levels. ...,<ul>\n<li>Gulf of Maine stock:\n<ul>\n<li>Acco...,Gadus morhua,...,33.1 mcg,100 g,1,54 mg,<p>Wild-caught from Maine to Virginia.</p>\n,0 g,<p>Atlantic cod has a mild clean flavor. It is...,<p>Cod has large flakes. It's less firm than h...,/profiles/atlantic-cod,02/17/2022 - 12:56

PREGUNTAS

In [23]:
import numpy as np

a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])

c=a*b
c

array([0, 0, 0, 0, 0])

In [24]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)

0

In [25]:
a=np.array([1,1,1,1,1])
a+10

array([11, 11, 11, 11, 11])